name: Data disco feature
description: Template for adding a feature
title: "✨(FEATURE) "
labels: [ ]
assignees: [ ]
projects: [ "HavierD/2"]
body:
  - type: markdown
    attributes:
      value: "|
        ## Data Disco Feature Request
"
  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: "This section should be like this: AS A [user persona], I WANT [user's needs], SO THAT [expected outcome]."
      placeholder: |
        AS A  xx
        I WANT xx
        SO THAT xx
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: "This section should describe the conditions that must be met for this issue to be considered complete."
      placeholder: |
        1. xxx must be able to do xx;
        2.
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: "This section should provide a detailed description of the feature being requested, including any relevant context or background information."
      placeholder: |
        This section should describe the conditions that must be met for this issue to be considered complete.
        1.
    validations:
      required: true

  - type: textarea
    id: related_tickets
    attributes:
      label: Related Tickets
      description: "This optional section should list any related tickets, such as bugs that this feature would fix or other features that are related to this one."

    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: "Please specify who needs to be notified after completion of this ticket, or remove this item if not applicable)"
      value: |
        - [ ] ...
        - [ ] Notify XXX
        - [ ] Clean up any AWS resources created during backlog work
        - [ ] DOD Link to checklist: https://utas.atlassian.net/wiki/spaces/IMOS/pages/488898620/Definition+of+Done+DOD
    validations:
      required: true

  - type: textarea
    id: prs
    attributes:
      label: PRs
      description: "This optional section should list any related Pull Requests"
      value: |
        Pull Request (PR) Review Guidelines: https://utas.atlassian.net/wiki/spaces/IMOS/pages/488996931/Pull+Request+PR+Review+Guidelines
        1.
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: "This optional section should list any dependencies that this feature has on other tickets or features."
      value: "1."

    validations:
      required: false

  - type: textarea
    id: demo
    attributes:
      label: Demo
      description: "This optional section should provide demos of the feature, if applicable."
      value: "1."

    validations:
      required: false
